# Generated by Django 5.2.1 on 2025-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('heater_temp', models.FloatField(blank=True, null=True)),
                ('epi_reflect1_1', models.FloatField(blank=True, null=True)),
                ('epi_reflect1_2', models.FloatField(blank=True, null=True)),
                ('epi_reflect1_3', models.FloatField(blank=True, null=True)),
                ('tmga_1_run', models.FloatField(blank=True, null=True)),
                ('tmal_1_run', models.FloatField(blank=True, null=True)),
                ('nh3_1_run', models.FloatField(blank=True, null=True)),
                ('sih4_1_run', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
