# Generated by Django 5.1.7 on 2025-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_alter_datafile_file_measurementresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementresult',
            name='angle_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='measurement_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementresult',
            name='variance_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
