# Generated by Django 5.1.7 on 2025-04-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_measurementresult_angle_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementresult',
            name='data_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='data_app.datafile'),
        ),
    ]
