# Generated by Django 5.1.7 on 2025-04-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_alter_measurementresult_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementresult',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='data_app.datafile'),
        ),
    ]
