# Generated by Django 5.2.1 on 2025-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0007_rawmeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmeasurement',
            name='data_file',
        ),
        migrations.AddField(
            model_name='rawmeasurement',
            name='data_file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
